FROM php:7.3-fpm-alpine

ENV \
  APP_DIR="/var/www"

#global docker update
RUN docker-php-ext-install pdo pdo_mysql
RUN apk add --update nodejs npm

# Install PHP extensions
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/bin/
RUN install-php-extensions ldap

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY ./src/myapp $APP_DIR
RUN chown -R www-data:www-data /var/www
RUN chmod -R 755 /var/www/storage

# Set working directory
WORKDIR $APP_DIR

RUN cd $APP_DIR && composer install
RUN npm install && npm run dev

# Optimisation? - script for build
#copy ./myStartupScript.sh /tmp
#ENTRYPOINT ["/tmp/myStartupScript.sh"]
