FROM php:7.3-fpm-alpine

LABEL maintainer="Marc Masure <masure.marc.59@gmail.com>"

ARG BUILD_DEVELOPMENT

ENV \
  APP_DIR="/var/www"

#global docker update
RUN docker-php-ext-install pdo pdo_mysql
RUN apk add --update nodejs npm

# Install PHP extensions
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/bin/
RUN install-php-extensions ldap

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY ./src/myapp $APP_DIR
COPY ./src/env $APP_DIR

# clear local packages
RUN rm -rf /var/www/composer && rm -rf /var/www/node_modules
RUN rm /var/www/composer.lock && rm /var/www/package-lock.json

RUN chown -R www-data:www-data /var/www
RUN chmod -R 755 /var/www/storage

# Set working directory
WORKDIR $APP_DIR

#RUN if [ "$BUILD_DEVELOPMENT" = "prod" ]; then \
RUN cd $APP_DIR && composer install
RUN npm install && npm run dev
#fi

RUN php artisan key:generate

# Optimisation? - script for build
#copy ./myStartupScript.sh /tmp
#ENTRYPOINT ["/tmp/myStartupScript.sh"]
